/**
 * POST /api/contact
 *
 * Cloudflare Pages Function that handles contact form submissions.
 *
 * Responsibilities:
 * - Receives POST requests from the site contact form
 * - Verifies the Cloudflare Turnstile token to prevent spam/bot submissions
 * - Parses and validates form input data
 * - FUTURE STEP: Forwards the message to the configured email destination
 * - Returns a JSON response indicating success or failure
 *
 * Environment:
 * - Runs on the Cloudflare edge via Pages Functions
 * - Executed server-side (never exposed to the browser)
 *
 * Security notes:
 * - The Turnstile secret key is read from environment variables
 * - The secret key must never be exposed to client-side JavaScript
 *
 * Expected request:
 * - Method: POST
 * - Content-Type: application/x-www-form-urlencoded or multipart/form-data
 * - Includes `cf-turnstile-response` generated by the Turnstile widget
 *
 * Expected response:
 * - JSON object with a success or error message
 *
 * This file acts as the server-side boundary between the public contact form
 * and private infrastructure (validation, email delivery).
 */

type Env = {
    TURNSTILE_SECRET_KEY: string;
};

type VerifyResponse = {
    success: boolean;
};

type ApiResponse = 
    | { ok: true; message: string }
    | { 
        ok: false;
        message: string;
        field?: "name" | "email" | "reason" | "message" | "turnstile" 
      };

function json(status: number, data: ApiResponse): Response {
    return new Response(JSON.stringify(data), {
        status,
        headers: { "Content-Type": "application/json; charset=utf-8" },
    });
}

export async function onRequestPost(context: {
    request: Request;
    env: Env;
}): Promise<Response> {
    const { request, env } = context;

    const formData = await request.formData();
    const name = String(formData.get("name") ?? "").trim();
    const email = String(formData.get("email") ?? "").trim();
    const reason = String(formData.get("reason") ?? "").trim();
    const message = String(formData.get("message") ?? "").trim();

    const token = String(formData.get("cf-turnstile-response") ?? "").trim();
    if (!name || !email || !reason || !message) {
        return json(400, { ok: false, message: "Please complete all required fields." });
    }

    if (!token) {
        return json(400, { ok: false, message: "Please complete the Captcha.", field: "turnstile" });
    }

    const ip = request.headers.get("CF-Connecting-IP") || "";

    const verifyBody = new URLSearchParams();
    verifyBody.append("secret", env.TURNSTILE_SECRET_KEY);
    verifyBody.append("response", token);
    if (ip) verifyBody.append("remoteip", ip);

    const verifyRes = await fetch(
        "https://challenges.cloudflare.com/turnstile/v0/siteverify", 
        {
            method: "POST",
            headers: { "Content-Type": "application/x-www-form-urlencoded" },
            body: verifyBody.toString(),
        }
    );

    const verifyJson = (await verifyRes.json()) as VerifyResponse;

    if (!verifyJson.success) {
        return json(403, { ok: false, message: "Captcha verification failed. Please try again.", field = "turnstile" });
    }

    return json(200, { 
        ok: true, 
        message: 
            "Thank you for messaging me! Your message has been sent successfully. I will be in contact with you within the next business day.",
    });
}