/**
 * POST /api/contact
 *
 * Cloudflare Pages Function that handles contact form submissions.
 *
 * Responsibilities:
 * - Receives POST requests from the site contact form
 * - Verifies the Cloudflare Turnstile token to prevent spam/bot submissions
 * - Parses and validates form input data
 * - FUTURE STEP: Forwards the message to the configured email destination
 * - Returns a JSON response indicating success or failure
 *
 * Environment:
 * - Runs on the Cloudflare edge via Pages Functions
 * - Executed server-side (never exposed to the browser)
 *
 * Security notes:
 * - The Turnstile secret key is read from environment variables
 * - The secret key must never be exposed to client-side JavaScript
 *
 * Expected request:
 * - Method: POST
 * - Content-Type: application/x-www-form-urlencoded or multipart/form-data
 * - Includes `cf-turnstile-response` generated by the Turnstile widget
 *
 * Expected response:
 * - JSON object with a success or error message
 *
 * This file acts as the server-side boundary between the public contact form
 * and private infrastructure (validation, email delivery).
 */

//TODO: Review variable naming conventions


//-------Types-------

type Env = {
    TURNSTILE_SECRET_KEY: string;
    RESEND_API_KEY: string;
    CONTACT_FROM_EMAIL: string;
    CONTACT_TO_EMAIL: string;
};

type TurnstileVerifyResponse = {
    success: boolean;
};

type ApiResponse = 
    | { ok: true; message: string }
    | { 
        ok: false;
        message: string;
        field?: "name" | "email" | "reason" | "message" | "turnstile" 
      };

//-------Constants-------

const TURNSTILE_VERIFY_URL = "https://challenges.cloudflare.com/turnstile/v0/siteverify";
const RESEND_EMAILS_URL = "https://api.resend.com/emails";
const ALLOWED_REASONS = new Set([
    "General question",
    "Website build or update",
    "Project support or technical services",
    "General work request",
    "Not sure yet, just want to talk",
    "Other inquiry",
]);

//-------Helpers-------

function readString(formData: FormData, key: string): string {
    return String(formData.get(key) ?? "").trim();
}

function isProbablyEmail(value: string): boolean {
    return /^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(value);
}

function json(status: number, data: ApiResponse): Response {
    return new Response(JSON.stringify(data), {
        status,
        headers: { 
            "Content-Type": "application/json; charset=utf-8",
            "Cache-Control": "no-store",
        },
    });
}

/**
 * Sends the contact form email via Resend.
 * 
 * Returns a small success object with an email id, or a failure object with an error message.
 * This keeps the handler focused on request/validation flow instead of email API details.
 */

async function sendContactEmail(params: {
    resendApiKey: string;
    from: string;
    to: string;
    name: string;
    email: string;
    reason: string;
    message: string;
}): Promise<{ ok: true; id: string } | { ok: false; error: string }> {
    const subject = `New contact form message: ${params.reason}`;

    const text =
        `New message from your website contact form\n\n` +
        `Name: ${params.name}\n` +
        `Email: ${params.email}\n` +
        `Reason: ${params.reason}\n\n` +
        `Message:\n${params.message}\n`;

    const res = await fetch(RESEND_EMAILS_URL, {
        method: "POST",
        headers: {
            "Content-Type": "application/json",
            Authorization: `Bearer ${params.resendApiKey}`,
        },
        body: JSON.stringify({
            from: params.from,
            to: params.to,
            subject,
            text,
            // Resend expects snake_case for this field name.
            reply_to: params.email,
        }),
    });

    const data = (await res.json()) as { id?: string; message?: string };

    if (!res.ok || !data.id) {
        return {
            ok: false,
            error: data.message ?? "Resend failed to send email.",
        };
    }

    return { ok: true, id: data.id };
}

//-------Handler-------

export async function onRequestPost(context: {
    request: Request;
    env: Env;
}): Promise<Response> {
    const { request, env } = context;

    const formData = await request.formData();
    const website = readString(formData, "website");
    const name = readString(formData, "name");
    const email = readString(formData, "email");
    const reason = readString(formData, "reason");
    const message = readString(formData, "message");
    const token = readString(formData, "cf-turnstile-response");

    // Honeypot check.
    if (website) {
        return json(400, { ok: false, message: "Invalid submission." });
    }

    if (!name) return json(400, { ok: false, message: "Please enter your name.", field: "name" });
    if (!email) return json(400, { ok: false, message: "Please enter your email.", field: "email" });
    if (!reason) return json(400, { ok: false, message: "Please choose a reason.", field: "reason" });
    if (!message) return json(400, { ok: false, message: "Please enter a message.", field: "message" });
    
    if (!isProbablyEmail(email)) {
        return json(400, { ok: false, message: "Please enter a valid email address.", field: "email" });
    }

    if (!ALLOWED_REASONS.has(reason)) {
        return json(400, { ok: false, message: "Please choose a valid reason.", field: "reason" });
    }

    if (name.length > 80) return json(400, { ok: false, message: "Name is too long.", field: "name" });
    if (email.length > 254) return json(400, { ok: false, message: "Email is too long.", field: "email"});
    if (message.length > 5000) return json(400, { ok: false, message: "Message is too long (max 5,000 characters).", field: "message" });

    if (!token) {
        return json(400, { ok: false, message: "Please complete the Captcha.", field: "turnstile" });
    }

    const ip = request.headers.get("CF-Connecting-IP") || "";

    const verifyBody = new URLSearchParams();
    verifyBody.append("secret", env.TURNSTILE_SECRET_KEY);
    verifyBody.append("response", token);
    if (ip) verifyBody.append("remoteip", ip);

    let verifyRes: Response;
    
    try {
        verifyRes = await fetch(TURNSTILE_VERIFY_URL, {
            method: "POST",
            headers: { "Content-Type": "application/x-www-form-urlencoded" },
            body: verifyBody.toString(),
        });
    } catch {
        return json(502, {
            ok: false,
            message: "Captcha verification failed due to a network error. Please try again.", field: "turnstile",
        });
    }

    if (!verifyRes.ok) {
        return json(502, {
            ok: false,
            message: "Captcha verification failed. Please try again.",
            field: "turnstile",
        });
    }

    const verifyJson = (await verifyRes.json()) as TurnstileVerifyResponse;

    if (!verifyJson.success) {
        return json(403, { ok: false, message: "Captcha verification failed. Please try again.", field: "turnstile" });
    }
    
    const resendApiKey = env.RESEND_API_KEY;
    const from = env.CONTACT_FROM_EMAIL;
    const to = env.CONTACT_TO_EMAIL;

    if (!resendApiKey || !from || !to) {
        return json(500, { ok: false, message: "Server email is not configured yet." });
    }

    const sendResult = await sendContactEmail({
        resendApiKey,
        from,
        to,
        name,
        email,
        reason,
        message,
    });

    if (!sendResult.ok) {
        return json(502, { ok: false, message: "Message received, but failed to send email. Please try again." }); //TODO Create better message
    }

    return json(200, { 
        ok: true, 
        message: 
            "Thank you for messaging me! Your message has been sent successfully. I will be in contact with you within the next business day.",
    });

}
